// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;
using System.Drawing;
using System.Runtime.CompilerServices;
using Microsoft.VisualBasic;

namespace WinPaletter.My
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    [HideModuleName()]
    public static class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan == null)
                {
                    var temp = new System.Resources.ResourceManager("WinPaletter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap AC_10_Dark
        {
            get
            {
                var obj = ResourceManager.GetObject("AC_10_Dark", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap AC_10_Light
        {
            get
            {
                var obj = ResourceManager.GetObject("AC_10_Light", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap AC_11_Dark
        {
            get
            {
                var obj = ResourceManager.GetObject("AC_11_Dark", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap AC_11_Light
        {
            get
            {
                var obj = ResourceManager.GetObject("AC_11_Light", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap add_win10
        {
            get
            {
                var obj = ResourceManager.GetObject("add_win10", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap add_win11
        {
            get
            {
                var obj = ResourceManager.GetObject("add_win11", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap add_win7
        {
            get
            {
                var obj = ResourceManager.GetObject("add_win7", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap add_win8
        {
            get
            {
                var obj = ResourceManager.GetObject("add_win8", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap add_winvista
        {
            get
            {
                var obj = ResourceManager.GetObject("add_winvista", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap add_winxp
        {
            get
            {
                var obj = ResourceManager.GetObject("add_winxp", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap AeroGlass
        {
            get
            {
                var obj = ResourceManager.GetObject("AeroGlass", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap AeroPeek
        {
            get
            {
                var obj = ResourceManager.GetObject("AeroPeek", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Assemblies
        {
            get
            {
                var obj = ResourceManager.GetObject("Assemblies", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap BackgroundOpacity
        {
            get
            {
                var obj = ResourceManager.GetObject("BackgroundOpacity", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap BasicTaskbar
        {
            get
            {
                var obj = ResourceManager.GetObject("BasicTaskbar", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CF_Img_Blue_yellow_tritanopia
        {
            get
            {
                var obj = ResourceManager.GetObject("CF_Img_Blue_yellow_tritanopia", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CF_Img_Grayscale
        {
            get
            {
                var obj = ResourceManager.GetObject("CF_Img_Grayscale", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CF_Img_Normal
        {
            get
            {
                var obj = ResourceManager.GetObject("CF_Img_Normal", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CF_Img_Red_green_green_weak_deuteranopia
        {
            get
            {
                var obj = ResourceManager.GetObject("CF_Img_Red_green_green_weak_deuteranopia", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CF_Img_Red_green_red_weak_protanopia
        {
            get
            {
                var obj = ResourceManager.GetObject("CF_Img_Red_green_red_weak_protanopia", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CF_Pie_Blue_yellow__tritanopia
        {
            get
            {
                var obj = ResourceManager.GetObject("CF_Pie_Blue_yellow__tritanopia", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CF_Pie_Grayscale
        {
            get
            {
                var obj = ResourceManager.GetObject("CF_Pie_Grayscale", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CF_Pie_Normal
        {
            get
            {
                var obj = ResourceManager.GetObject("CF_Pie_Normal", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CF_Pie_Red_green_green_weak_deuteranopia
        {
            get
            {
                var obj = ResourceManager.GetObject("CF_Pie_Red_green_green_weak_deuteranopia", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CF_Pie_Red_green_red_weak_protanopia
        {
            get
            {
                var obj = ResourceManager.GetObject("CF_Pie_Red_green_red_weak_protanopia", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap checker_disabled
        {
            get
            {
                var obj = ResourceManager.GetObject("checker_disabled", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap checker_enabled
        {
            get
            {
                var obj = ResourceManager.GetObject("checker_enabled", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_10x18
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_10x18", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_10x18_P
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_10x18_P", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_12x16
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_12x16", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_12x16_P
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_12x16_P", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_16x12
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_16x12", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_16x12_P
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_16x12_P", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_16x8
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_16x8", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_16x8_P
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_16x8_P", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_4x6
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_4x6", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_4x6_P
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_4x6_P", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_5x12
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_5x12", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_5x12_P
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_5x12_P", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_6x8
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_6x8", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_6x8_P
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_6x8_P", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_7x12
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_7x12", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_7x12_P
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_7x12_P", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_8x12
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_8x12", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_8x12_P
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_8x12_P", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_8x8
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_8x8", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CMD_8x8_P
        {
            get
            {
                var obj = ResourceManager.GetObject("CMD_8x8_P", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap darkmode_dark
        {
            get
            {
                var obj = ResourceManager.GetObject("darkmode_dark", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap darkmode_light
        {
            get
            {
                var obj = ResourceManager.GetObject("darkmode_light", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static Icon fileextension
        {
            get
            {
                var obj = ResourceManager.GetObject("fileextension", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap GaussianBlur
        {
            get
            {
                var obj = ResourceManager.GetObject("GaussianBlur", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap GaussianBlurOpaque
        {
            get
            {
                var obj = ResourceManager.GetObject("GaussianBlurOpaque", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static Icon Icon_Uninstall
        {
            get
            {
                var obj = ResourceManager.GetObject("Icon_Uninstall", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static Icon icons8_command_line
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_command_line", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static Icon icons8_PowerShell
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_PowerShell", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] JetBrainsMono_Medium
        {
            get
            {
                var obj = ResourceManager.GetObject("JetBrainsMono_Medium", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap LangNode_JSON
        {
            get
            {
                var obj = ResourceManager.GetObject("LangNode_JSON", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap LangNode_Main
        {
            get
            {
                var obj = ResourceManager.GetObject("LangNode_Main", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap LangNode_Value
        {
            get
            {
                var obj = ResourceManager.GetObject("LangNode_Value", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to MIT License
        /// 
        /// Copyright (c) 2022-2023 Abdelrhman-AK
        /// 
        /// Permission is hereby granted, free of charge, to any person obtaining a copy
        /// of this software and associated documentation files (the &quot;Software&quot;), to deal
        /// in the Software without restriction, including without limitation the rights
        /// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        /// copies of the Software, and to permit persons to whom the Software is
        /// furnished to do so, subject to the following conditions:
        /// 
        /// The above copyr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LICENSE
        {
            get
            {
                return ResourceManager.GetString("LICENSE", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap lightmode_dark
        {
            get
            {
                var obj = ResourceManager.GetObject("lightmode_dark", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap lightmode_light
        {
            get
            {
                var obj = ResourceManager.GetObject("lightmode_light", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/blob/master/CHANGELOG.md.
        /// </summary>
        public static string Link_Changelog
        {
            get
            {
                return ResourceManager.GetString("Link_Changelog", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/blob/master/License.md?raw=true.
        /// </summary>
        public static string Link_License
        {
            get
            {
                return ResourceManager.GetString("Link_License", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/releases.
        /// </summary>
        public static string Link_Releases
        {
            get
            {
                return ResourceManager.GetString("Link_Releases", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/.
        /// </summary>
        public static string Link_Repository
        {
            get
            {
                return ResourceManager.GetString("Link_Repository", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/blob/master/Store/store.wpdb?raw=true.
        /// </summary>
        public static string Link_StoreMainDB
        {
            get
            {
                return ResourceManager.GetString("Link_StoreMainDB", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/wiki/Create-an-online-WinPaletter-Store-source-(server%5CGitHub-repository)-for-hosting-WinPaletter-themes.
        /// </summary>
        public static string Link_StoreOnlineSourceCreation
        {
            get
            {
                return ResourceManager.GetString("Link_StoreOnlineSourceCreation", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter-Store/blob/main/store.wpdb?raw=true.
        /// </summary>
        public static string Link_StoreReposDB
        {
            get
            {
                return ResourceManager.GetString("Link_StoreReposDB", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/wiki/WinPaletter-Sources-extension.
        /// </summary>
        public static string Link_StoreSourcesExtension
        {
            get
            {
                return ResourceManager.GetString("Link_StoreSourcesExtension", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/wiki/Upload-themes-to-WinPaletter-Store-repository.
        /// </summary>
        public static string Link_StoreUpload
        {
            get
            {
                return ResourceManager.GetString("Link_StoreUpload", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/blob/master/UpdatesConfig/Updates?raw=true.
        /// </summary>
        public static string Link_Updates
        {
            get
            {
                return ResourceManager.GetString("Link_Updates", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/wiki.
        /// </summary>
        public static string Link_Wiki
        {
            get
            {
                return ResourceManager.GetString("Link_Wiki", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap LogonUI7
        {
            get
            {
                var obj = ResourceManager.GetObject("LogonUI7", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap LogonUI8
        {
            get
            {
                var obj = ResourceManager.GetObject("LogonUI8", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] luna
        {
            get
            {
                var obj = ResourceManager.GetObject("luna", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Mini_AC
        {
            get
            {
                var obj = ResourceManager.GetObject("Mini_AC", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Mini_ACHover_Links
        {
            get
            {
                var obj = ResourceManager.GetObject("Mini_ACHover_Links", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Mini_Badge
        {
            get
            {
                var obj = ResourceManager.GetObject("Mini_Badge", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Mini_Hamburger
        {
            get
            {
                var obj = ResourceManager.GetObject("Mini_Hamburger", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Mini_Lines_Toggles_Buttons
        {
            get
            {
                var obj = ResourceManager.GetObject("Mini_Lines_Toggles_Buttons", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Mini_Overflow
        {
            get
            {
                var obj = ResourceManager.GetObject("Mini_Overflow", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Mini_PressedButton
        {
            get
            {
                var obj = ResourceManager.GetObject("Mini_PressedButton", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Mini_Settings_Icons
        {
            get
            {
                var obj = ResourceManager.GetObject("Mini_Settings_Icons", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Mini_StartContextMenu
        {
            get
            {
                var obj = ResourceManager.GetObject("Mini_StartContextMenu", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Mini_StartMenu
        {
            get
            {
                var obj = ResourceManager.GetObject("Mini_StartMenu", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Mini_StartMenu_Taskbar_AC
        {
            get
            {
                var obj = ResourceManager.GetObject("Mini_StartMenu_Taskbar_AC", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Mini_Taskbar
        {
            get
            {
                var obj = ResourceManager.GetObject("Mini_Taskbar", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Mini_TaskbarActiveIcon
        {
            get
            {
                var obj = ResourceManager.GetObject("Mini_TaskbarActiveIcon", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Mini_TaskbarApp
        {
            get
            {
                var obj = ResourceManager.GetObject("Mini_TaskbarApp", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Mini_Undefined
        {
            get
            {
                var obj = ResourceManager.GetObject("Mini_Undefined", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Mini_UWPDlg
        {
            get
            {
                var obj = ResourceManager.GetObject("Mini_UWPDlg", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Native10
        {
            get
            {
                var obj = ResourceManager.GetObject("Native10", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Native11
        {
            get
            {
                var obj = ResourceManager.GetObject("Native11", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Native7
        {
            get
            {
                var obj = ResourceManager.GetObject("Native7", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Native8
        {
            get
            {
                var obj = ResourceManager.GetObject("Native8", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap NativeVista
        {
            get
            {
                var obj = ResourceManager.GetObject("NativeVista", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap NativeXP
        {
            get
            {
                var obj = ResourceManager.GetObject("NativeXP", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_administrator
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_administrator", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_applying
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_applying", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_dll
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_dll", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_error
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_error", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_file_rename
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_file_rename", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_info
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_info", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_pe_backup
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_pe_backup", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_pe_patch
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_pe_patch", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_pe_restore
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_pe_restore", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_reg_add
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_reg_add", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_reg_delete
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_reg_delete", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_reg_skip
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_reg_skip", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_skip
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_skip", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_success
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_success", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_task_add
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_task_add", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_task_remove
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_task_remove", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_time
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_time", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_update
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_update", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap notify_warning
        {
            get
            {
                var obj = ResourceManager.GetObject("notify_warning", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap PS_10x18
        {
            get
            {
                var obj = ResourceManager.GetObject("PS_10x18", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap PS_12x16
        {
            get
            {
                var obj = ResourceManager.GetObject("PS_12x16", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap PS_16x12
        {
            get
            {
                var obj = ResourceManager.GetObject("PS_16x12", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap PS_16x8
        {
            get
            {
                var obj = ResourceManager.GetObject("PS_16x8", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap PS_4x6
        {
            get
            {
                var obj = ResourceManager.GetObject("PS_4x6", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap PS_5x12
        {
            get
            {
                var obj = ResourceManager.GetObject("PS_5x12", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap PS_6x8
        {
            get
            {
                var obj = ResourceManager.GetObject("PS_6x8", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap PS_7x12
        {
            get
            {
                var obj = ResourceManager.GetObject("PS_7x12", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap PS_8x12
        {
            get
            {
                var obj = ResourceManager.GetObject("PS_8x12", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap PS_8x8
        {
            get
            {
                var obj = ResourceManager.GetObject("PS_8x8", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Aero Fallback (Windows Vista-11)|ActiveBorder=180 180 180|ActiveTitle=153 180 209|AppWorkspace=171 171 171|Background=0 0 0|ButtonAlternateFace=0 0 0|ButtonDkShadow=105 105 105|ButtonFace=240 240 240|ButtonHilight=255 255 255|ButtonLight=227 227 227|ButtonShadow=160 160 160|ButtonText=0 0 0|GradientActiveTitle=185 209 234|GradientInactiveTitle=215 228 242|GrayText=109 109 109|HilightText=255 255 255|HotTrackingColor=0 102 204|InactiveBorder=244 247 252|InactiveTitle=191 205 219|InactiveTitleText=0 0 0|InfoT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RetroThemesDB
        {
            get
            {
                return ResourceManager.GetString("RetroThemesDB", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SampleApp_Active
        {
            get
            {
                var obj = ResourceManager.GetObject("SampleApp_Active", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SampleApp_Inactive
        {
            get
            {
                var obj = ResourceManager.GetObject("SampleApp_Inactive", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SampleApp_Small_Active
        {
            get
            {
                var obj = ResourceManager.GetObject("SampleApp_Small_Active", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SampleApp_Small_Inactive
        {
            get
            {
                var obj = ResourceManager.GetObject("SampleApp_Small_Inactive", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static Icon settingsfile
        {
            get
            {
                var obj = ResourceManager.GetObject("settingsfile", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Sound_Play
        {
            get
            {
                var obj = ResourceManager.GetObject("Sound_Play", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Sound_Stop
        {
            get
            {
                var obj = ResourceManager.GetObject("Sound_Stop", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Start10_Dark
        {
            get
            {
                var obj = ResourceManager.GetObject("Start10_Dark", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Start10_Light
        {
            get
            {
                var obj = ResourceManager.GetObject("Start10_Light", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Start11_Dark
        {
            get
            {
                var obj = ResourceManager.GetObject("Start11_Dark", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Start11_EP_Rounded_Dark
        {
            get
            {
                var obj = ResourceManager.GetObject("Start11_EP_Rounded_Dark", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Start11_EP_Rounded_Light
        {
            get
            {
                var obj = ResourceManager.GetObject("Start11_EP_Rounded_Light", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Start11_Light
        {
            get
            {
                var obj = ResourceManager.GetObject("Start11_Light", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Start7
        {
            get
            {
                var obj = ResourceManager.GetObject("Start7", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Start7Basic
        {
            get
            {
                var obj = ResourceManager.GetObject("Start7Basic", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Start7Glass
        {
            get
            {
                var obj = ResourceManager.GetObject("Start7Glass", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap StartBtn_10Dark
        {
            get
            {
                var obj = ResourceManager.GetObject("StartBtn_10Dark", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap StartBtn_10Light
        {
            get
            {
                var obj = ResourceManager.GetObject("StartBtn_10Light", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap StartBtn_11_EP
        {
            get
            {
                var obj = ResourceManager.GetObject("StartBtn_11_EP", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap StartBtn_11Dark
        {
            get
            {
                var obj = ResourceManager.GetObject("StartBtn_11Dark", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap StartBtn_11Light
        {
            get
            {
                var obj = ResourceManager.GetObject("StartBtn_11Light", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_BackBtn
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_BackBtn", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_DesignedFor10
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_DesignedFor10", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_DesignedFor11
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_DesignedFor11", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_DesignedFor7
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_DesignedFor7", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_DesignedFor8
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_DesignedFor8", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_DesignedForVista
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_DesignedForVista", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_DesignedForXP
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_DesignedForXP", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_DoneByUser
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_DoneByUser", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_DoneByWinPaletter
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_DoneByWinPaletter", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_Pattern1
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_Pattern1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_Pattern10
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_Pattern10", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_Pattern2
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_Pattern2", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_Pattern3
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_Pattern3", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_Pattern4
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_Pattern4", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_Pattern5
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_Pattern5", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_Pattern6
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_Pattern6", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_Pattern7
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_Pattern7", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_Pattern8
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_Pattern8", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_Pattern9
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_Pattern9", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Store_ThemeVersion
        {
            get
            {
                var obj = ResourceManager.GetObject("Store_ThemeVersion", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Taskbar_ActiveApp7
        {
            get
            {
                var obj = ResourceManager.GetObject("Taskbar_ActiveApp7", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Taskbar_InactiveApp7
        {
            get
            {
                var obj = ResourceManager.GetObject("Taskbar_InactiveApp7", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static Icon ThemesResIcon
        {
            get
            {
                var obj = ResourceManager.GetObject("ThemesResIcon", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Update
        {
            get
            {
                var obj = ResourceManager.GetObject("Update", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Update_Dot
        {
            get
            {
                var obj = ResourceManager.GetObject("Update_Dot", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Vista_ActiveApp
        {
            get
            {
                var obj = ResourceManager.GetObject("Vista_ActiveApp", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Vista_Close_Active
        {
            get
            {
                var obj = ResourceManager.GetObject("Vista_Close_Active", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Vista_Close_inactive
        {
            get
            {
                var obj = ResourceManager.GetObject("Vista_Close_inactive", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Vista_InactiveApp
        {
            get
            {
                var obj = ResourceManager.GetObject("Vista_InactiveApp", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Vista_StartAero
        {
            get
            {
                var obj = ResourceManager.GetObject("Vista_StartAero", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Vista_StartBasic
        {
            get
            {
                var obj = ResourceManager.GetObject("Vista_StartBasic", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Vista_StartLowerORB
        {
            get
            {
                var obj = ResourceManager.GetObject("Vista_StartLowerORB", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Vista_Taskbar
        {
            get
            {
                var obj = ResourceManager.GetObject("Vista_Taskbar", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win10x_Close_Dark
        {
            get
            {
                var obj = ResourceManager.GetObject("Win10x_Close_Dark", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win10x_Close_Light
        {
            get
            {
                var obj = ResourceManager.GetObject("Win10x_Close_Light", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win7_Basic_Close_0
        {
            get
            {
                var obj = ResourceManager.GetObject("Win7_Basic_Close_0", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win7_Basic_Close_1
        {
            get
            {
                var obj = ResourceManager.GetObject("Win7_Basic_Close_1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win7_Basic_Close_2
        {
            get
            {
                var obj = ResourceManager.GetObject("Win7_Basic_Close_2", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win7_Basic_Close_ToolWindow
        {
            get
            {
                var obj = ResourceManager.GetObject("Win7_Basic_Close_ToolWindow", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win7_Close_Active
        {
            get
            {
                var obj = ResourceManager.GetObject("Win7_Close_Active", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win7_Close_inactive
        {
            get
            {
                var obj = ResourceManager.GetObject("Win7_Close_inactive", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win7_TitleTopL
        {
            get
            {
                var obj = ResourceManager.GetObject("Win7_TitleTopL", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win7_TitleTopR
        {
            get
            {
                var obj = ResourceManager.GetObject("Win7_TitleTopR", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win7AltTabBasicButton
        {
            get
            {
                var obj = ResourceManager.GetObject("Win7AltTabBasicButton", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win7ORB
        {
            get
            {
                var obj = ResourceManager.GetObject("Win7ORB", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win7Sides
        {
            get
            {
                var obj = ResourceManager.GetObject("Win7Sides", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win7TaskbarSides
        {
            get
            {
                var obj = ResourceManager.GetObject("Win7TaskbarSides", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win8_Close_0
        {
            get
            {
                var obj = ResourceManager.GetObject("Win8_Close_0", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win8_Close_1
        {
            get
            {
                var obj = ResourceManager.GetObject("Win8_Close_1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win8_Close_2
        {
            get
            {
                var obj = ResourceManager.GetObject("Win8_Close_2", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win8_Close_3
        {
            get
            {
                var obj = ResourceManager.GetObject("Win8_Close_3", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win8_Close_ToolWindow
        {
            get
            {
                var obj = ResourceManager.GetObject("Win8_Close_ToolWindow", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Win8ORB
        {
            get
            {
                var obj = ResourceManager.GetObject("Win8ORB", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap WP_Admin
        {
            get
            {
                var obj = ResourceManager.GetObject("WP_Admin", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        /// &lt;Task version=&quot;1.2&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        /// &lt;RegistrationInfo&gt;
        ///    &lt;Author&gt;WinPaletter, MuscularPuky&lt;/Author&gt;
        ///    &lt;Description&gt;Play charger connection sound forcibly on any version of Windows&lt;/Description&gt;
        ///    &lt;URI&gt;\WinPaletter\ChargerConnected&lt;/URI&gt;
        /// &lt;/RegistrationInfo&gt;
        /// &lt;Triggers&gt;
        ///    &lt;EventTrigger&gt;
        ///      &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///      &lt;Subscription&gt;&amp;lt;QueryList&amp;gt;&amp;lt;Query Id=&quot;0&quot; Path=&quot;System&quot;&amp;gt;&amp;lt;Select Path [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XML_ChargerConnected
        {
            get
            {
                return ResourceManager.GetString("XML_ChargerConnected", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        /// &lt;Task version=&quot;1.4&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        /// &lt;RegistrationInfo&gt;
        ///    &lt;Author&gt;WinPaletter&lt;/Author&gt;
        ///    &lt;Description&gt;Play Windows logoff sound forcibly on Windows 8 and higher&lt;/Description&gt;
        ///    &lt;URI&gt;\WinPaletter\Logoff&lt;/URI&gt;
        /// &lt;/RegistrationInfo&gt;
        /// &lt;Triggers&gt;
        ///    &lt;EventTrigger&gt;
        ///      &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///      &lt;Subscription&gt;&amp;lt;QueryList&amp;gt;&amp;lt;Query Id=&quot;0&quot; Path=&quot;Security&quot;&amp;gt;&amp;lt;Select Path=&quot;Security&quot;&amp;gt;*[System[Even [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XML_Logoff
        {
            get
            {
                return ResourceManager.GetString("XML_Logoff", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        /// &lt;Task version=&quot;1.4&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        /// &lt;RegistrationInfo&gt;
        ///    &lt;Author&gt;WinPaletter&lt;/Author&gt;
        ///    &lt;Description&gt;Play Windows logon sound forcibly on Windows 8 and higher&lt;/Description&gt;
        ///    &lt;URI&gt;\WinPaletter\Play logon sound&lt;/URI&gt;
        /// &lt;/RegistrationInfo&gt;
        /// &lt;Triggers&gt;
        ///    &lt;LogonTrigger&gt;
        ///      &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///    &lt;/LogonTrigger&gt;
        ///    &lt;SessionStateChangeTrigger&gt;
        ///      &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///      &lt;StateChange&gt;Con [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XML_Logon
        {
            get
            {
                return ResourceManager.GetString("XML_Logon", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        /// &lt;Task version=&quot;1.4&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        /// &lt;RegistrationInfo&gt;
        ///    &lt;Author&gt;WinPaletter&lt;/Author&gt;
        ///    &lt;Description&gt;Play Windows shutdown sound forcibly on Windows 8 and higher&lt;/Description&gt;
        ///    &lt;URI&gt;\WinPaletter\Play shutdown sound&lt;/URI&gt;
        /// &lt;/RegistrationInfo&gt;
        /// &lt;Triggers&gt;
        ///    &lt;EventTrigger&gt;
        ///      &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///      &lt;Subscription&gt;&amp;lt;QueryList&amp;gt;&amp;lt;Query Id=&quot;0&quot; Path=&quot;System&quot;&amp;gt;&amp;lt;Select Path=&quot;System&quot;&amp;gt;*[ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XML_Shutdown
        {
            get
            {
                return ResourceManager.GetString("XML_Shutdown", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        /// &lt;Task version=&quot;1.2&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        /// &lt;RegistrationInfo&gt;
        ///    &lt;Author&gt;WinPaletter, MuscularPukyy&lt;/Author&gt;
        ///    &lt;Description&gt;Play Windows account unlock sound forcibly on Windows 8 and higher&lt;/Description&gt;
        ///    &lt;URI&gt;\WinPaletter\Unlock&lt;/URI&gt;
        /// &lt;/RegistrationInfo&gt;
        /// &lt;Triggers&gt;
        ///    &lt;EventTrigger&gt;
        ///      &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///      &lt;Subscription&gt;&amp;lt;QueryList&amp;gt;&amp;lt;Query Id=&quot;0&quot; Path=&quot;Security&quot;&amp;gt;&amp;lt;Select Path=&quot;Sec [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XML_Unlock
        {
            get
            {
                return ResourceManager.GetString("XML_Unlock", resourceCulture);
            }
        }
    }
}