//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPaletter.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CMD_Raster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CMD_Raster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinPaletter.Assets.CMD_Raster", typeof(CMD_Raster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_10x18 {
            get {
                object obj = ResourceManager.GetObject("CMD_10x18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_10x18_P {
            get {
                object obj = ResourceManager.GetObject("CMD_10x18_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_12x16 {
            get {
                object obj = ResourceManager.GetObject("CMD_12x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_12x16_P {
            get {
                object obj = ResourceManager.GetObject("CMD_12x16_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_16x12 {
            get {
                object obj = ResourceManager.GetObject("CMD_16x12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_16x12_P {
            get {
                object obj = ResourceManager.GetObject("CMD_16x12_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_16x8 {
            get {
                object obj = ResourceManager.GetObject("CMD_16x8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_16x8_P {
            get {
                object obj = ResourceManager.GetObject("CMD_16x8_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_4x6 {
            get {
                object obj = ResourceManager.GetObject("CMD_4x6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_4x6_P {
            get {
                object obj = ResourceManager.GetObject("CMD_4x6_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_5x12 {
            get {
                object obj = ResourceManager.GetObject("CMD_5x12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_5x12_P {
            get {
                object obj = ResourceManager.GetObject("CMD_5x12_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_6x8 {
            get {
                object obj = ResourceManager.GetObject("CMD_6x8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_6x8_P {
            get {
                object obj = ResourceManager.GetObject("CMD_6x8_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_7x12 {
            get {
                object obj = ResourceManager.GetObject("CMD_7x12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_7x12_P {
            get {
                object obj = ResourceManager.GetObject("CMD_7x12_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_8x12 {
            get {
                object obj = ResourceManager.GetObject("CMD_8x12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_8x12_P {
            get {
                object obj = ResourceManager.GetObject("CMD_8x12_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_8x8 {
            get {
                object obj = ResourceManager.GetObject("CMD_8x8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Thumbnail.
        /// </summary>
        internal static System.Drawing.Bitmap CMD_8x8_P {
            get {
                object obj = ResourceManager.GetObject("CMD_8x8_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
