'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WinPaletter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property AC_10_Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AC_10_Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property AC_10_Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AC_10_Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property AC_11_Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AC_11_Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property AC_11_Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AC_11_Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property add_win10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_win10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property add_win11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_win11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property add_win7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_win7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property add_win8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_win8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property add_winvista() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_winvista", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property add_winxp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_winxp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property AeroGlass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AeroGlass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property AeroPeek() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AeroPeek", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property Animator() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Animator", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property AnimCur() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AnimCur", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BasicTaskbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BasicTaskbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CF_Img_Blue_yellow_tritanopia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CF_Img_Blue_yellow_tritanopia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CF_Img_Grayscale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CF_Img_Grayscale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CF_Img_Normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CF_Img_Normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CF_Img_Red_green_green_weak_deuteranopia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CF_Img_Red_green_green_weak_deuteranopia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CF_Img_Red_green_red_weak_protanopia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CF_Img_Red_green_red_weak_protanopia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CF_Pie_Blue_yellow__tritanopia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CF_Pie_Blue_yellow__tritanopia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CF_Pie_Grayscale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CF_Pie_Grayscale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CF_Pie_Normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CF_Pie_Normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CF_Pie_Red_green_green_weak_deuteranopia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CF_Pie_Red_green_green_weak_deuteranopia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CF_Pie_Red_green_red_weak_protanopia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CF_Pie_Red_green_red_weak_protanopia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property checker_disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checker_disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property checker_enabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checker_enabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_10x18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_10x18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_10x18_P() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_10x18_P", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_12x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_12x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_12x16_P() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_12x16_P", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_16x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_16x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_16x12_P() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_16x12_P", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_16x8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_16x8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_16x8_P() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_16x8_P", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_4x6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_4x6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_4x6_P() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_4x6_P", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_5x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_5x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_5x12_P() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_5x12_P", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_6x8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_6x8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_6x8_P() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_6x8_P", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_7x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_7x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_7x12_P() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_7x12_P", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_8x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_8x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_8x12_P() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_8x12_P", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_8x8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_8x8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CMD_8x8_P() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CMD_8x8_P", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property ColorThief_Desktop_v46() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ColorThief_Desktop_v46", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property Cyotek_Windows_Forms_ColorPicker() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Cyotek_Windows_Forms_ColorPicker", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property darkmode_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("darkmode_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property darkmode_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("darkmode_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property Devcorp_Controls_VisualStyles() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Devcorp_Controls_VisualStyles", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property fileextension() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("fileextension", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property GaussianBlur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GaussianBlur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property GaussianBlurOpaque() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GaussianBlurOpaque", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property Icon_Uninstall() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon_Uninstall", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property icons8_command_line() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_command_line", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property icons8_PowerShell() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_PowerShell", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property ImageProcessor() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageProcessor", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property JetBrainsMono_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("JetBrainsMono_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property LangNode_JSON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LangNode_JSON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property LangNode_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LangNode_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property LangNode_Value() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LangNode_Value", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIT License
        '''
        '''Copyright (c) 2022-2023 Abdelrhman-AK
        '''
        '''Permission is hereby granted, free of charge, to any person obtaining a copy
        '''of this software and associated documentation files (the &quot;Software&quot;), to deal
        '''in the Software without restriction, including without limitation the rights
        '''to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        '''copies of the Software, and to permit persons to whom the Software is
        '''furnished to do so, subject to the following conditions:
        '''
        '''The above copyr [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property LICENSE() As String
            Get
                Return ResourceManager.GetString("LICENSE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property lightmode_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lightmode_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property lightmode_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lightmode_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/blob/master/CHANGELOG.md.
        '''</summary>
        Public ReadOnly Property Link_Changelog() As String
            Get
                Return ResourceManager.GetString("Link_Changelog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/blob/master/WinPaletter%20Converter.exe.
        '''</summary>
        Public ReadOnly Property Link_Converter() As String
            Get
                Return ResourceManager.GetString("Link_Converter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/blob/master/License.md?raw=true.
        '''</summary>
        Public ReadOnly Property Link_License() As String
            Get
                Return ResourceManager.GetString("Link_License", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/releases.
        '''</summary>
        Public ReadOnly Property Link_Releases() As String
            Get
                Return ResourceManager.GetString("Link_Releases", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/.
        '''</summary>
        Public ReadOnly Property Link_Repository() As String
            Get
                Return ResourceManager.GetString("Link_Repository", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/blob/master/Store/store.wpdb?raw=true.
        '''</summary>
        Public ReadOnly Property Link_StoreMainDB() As String
            Get
                Return ResourceManager.GetString("Link_StoreMainDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter-Store/blob/main/store.wpdb?raw=true.
        '''</summary>
        Public ReadOnly Property Link_StoreReposDB() As String
            Get
                Return ResourceManager.GetString("Link_StoreReposDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/blob/master/UpdatesConfig/Updates?raw=true.
        '''</summary>
        Public ReadOnly Property Link_Updates() As String
            Get
                Return ResourceManager.GetString("Link_Updates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property LogonUI7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogonUI7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property LogonUI8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogonUI8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property luna() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("luna", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Luna_Start_Blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Luna_Start_Blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Luna_Start_OliveGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Luna_Start_OliveGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Luna_Start_Silver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Luna_Start_Silver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Luna_StartBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Luna_StartBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Mini_AC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_AC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Mini_ACHover_Links() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_ACHover_Links", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Mini_Badge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_Badge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Mini_Hamburger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_Hamburger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Mini_Lines_Toggles_Buttons() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_Lines_Toggles_Buttons", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Mini_Overflow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_Overflow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Mini_PressedButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_PressedButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Mini_Settings_Icons() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_Settings_Icons", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Mini_StartMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_StartMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Mini_StartMenu_Taskbar_AC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_StartMenu_Taskbar_AC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Mini_Taskbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_Taskbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Mini_TaskbarActiveIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_TaskbarActiveIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Mini_TaskbarApp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_TaskbarApp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Mini_Undefined() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_Undefined", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Mini_UWPDlg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_UWPDlg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Native10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Native10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Native11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Native11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Native7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Native7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Native8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Native8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property NativeVista() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NativeVista", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property NativeXP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NativeXP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property Newtonsoft_Json() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Newtonsoft_Json", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property notify_administrator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notify_administrator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property notify_error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notify_error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property notify_info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notify_info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property notify_skip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notify_skip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property notify_success() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notify_success", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property notify_time() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notify_time", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property notify_update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notify_update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property notify_warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notify_warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property Ookii_Dialogs_WinForms() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ookii_Dialogs_WinForms", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PS_10x18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PS_10x18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PS_12x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PS_12x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PS_16x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PS_16x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PS_16x8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PS_16x8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PS_4x6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PS_4x6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PS_5x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PS_5x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PS_6x8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PS_6x8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PS_7x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PS_7x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PS_8x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PS_8x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PS_8x8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PS_8x8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aero Fallback (Windows Vista-11)|ActiveBorder=180 180 180|ActiveTitle=153 180 209|AppWorkspace=171 171 171|Background=0 0 0|ButtonAlternateFace=0 0 0|ButtonDkShadow=105 105 105|ButtonFace=240 240 240|ButtonHilight=255 255 255|ButtonLight=227 227 227|ButtonShadow=160 160 160|ButtonText=0 0 0|GradientActiveTitle=185 209 234|GradientInactiveTitle=215 228 242|GrayText=109 109 109|HilightText=255 255 255|HotTrackingColor=0 102 204|InactiveBorder=244 247 252|InactiveTitle=191 205 219|InactiveTitleText=0 0 0|InfoT [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property RetroThemesDB() As String
            Get
                Return ResourceManager.GetString("RetroThemesDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SampleApp_Active() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SampleApp_Active", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SampleApp_Inactive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SampleApp_Inactive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SampleApp_Small_Active() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SampleApp_Small_Active", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SampleApp_Small_Inactive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SampleApp_Small_Inactive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property settingsfile() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("settingsfile", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Sound_Play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sound_Play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Sound_Stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sound_Stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Start10_Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start10_Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Start10_Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start10_Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Start11_Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start11_Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Start11_EP_Rounded_Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start11_EP_Rounded_Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Start11_EP_Rounded_Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start11_EP_Rounded_Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Start11_Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start11_Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Start7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Start7Basic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start7Basic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Start7Glass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start7Glass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property StartBtn_10Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartBtn_10Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property StartBtn_10Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartBtn_10Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property StartBtn_11_EP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartBtn_11_EP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property StartBtn_11Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartBtn_11Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property StartBtn_11Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartBtn_11Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_BackBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_BackBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_DesignedFor10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_DesignedFor10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_DesignedFor11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_DesignedFor11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_DesignedFor7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_DesignedFor7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_DesignedFor8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_DesignedFor8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_DesignedForVista() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_DesignedForVista", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_DesignedForXP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_DesignedForXP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_DoneByUser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_DoneByUser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_DoneByWinPaletter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_DoneByWinPaletter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_Pattern1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_Pattern1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_Pattern10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_Pattern10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_Pattern2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_Pattern2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_Pattern3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_Pattern3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_Pattern4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_Pattern4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_Pattern5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_Pattern5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_Pattern6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_Pattern6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_Pattern7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_Pattern7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_Pattern8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_Pattern8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Store_Pattern9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store_Pattern9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property System_Buffers() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("System_Buffers", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property System_Memory() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("System_Memory", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property System_Numerics_Vectors() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("System_Numerics_Vectors", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property System_Resources_Extensions() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("System_Resources_Extensions", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property System_Runtime_CompilerServices_Unsafe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("System_Runtime_CompilerServices_Unsafe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property System_ValueTuple() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("System_ValueTuple", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Taskbar_ActiveApp7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Taskbar_ActiveApp7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Taskbar_InactiveApp7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Taskbar_InactiveApp7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property ThemesResIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ThemesResIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Update_Dot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Update_Dot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Vista_ActiveApp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista_ActiveApp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Vista_Close_Active() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista_Close_Active", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Vista_Close_inactive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista_Close_inactive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Vista_InactiveApp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista_InactiveApp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Vista_StartAero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista_StartAero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Vista_StartBasic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista_StartBasic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Vista_StartLowerORB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista_StartLowerORB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Vista_Taskbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista_Taskbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win10x_Close_Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win10x_Close_Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win10x_Close_Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win10x_Close_Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win7_Basic_Close_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7_Basic_Close_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win7_Basic_Close_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7_Basic_Close_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win7_Basic_Close_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7_Basic_Close_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win7_Basic_Close_ToolWindow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7_Basic_Close_ToolWindow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win7_Close_Active() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7_Close_Active", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win7_Close_inactive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7_Close_inactive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win7_TitleTopL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7_TitleTopL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win7_TitleTopR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7_TitleTopR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win7AltTabBasicButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7AltTabBasicButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win7ORB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7ORB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win7Sides() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7Sides", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win7TaskbarSides() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7TaskbarSides", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win8_Close_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win8_Close_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win8_Close_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win8_Close_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win8_Close_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win8_Close_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win8_Close_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win8_Close_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win8_Close_ToolWindow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win8_Close_ToolWindow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Win8ORB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win8ORB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property WP_Admin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WP_Admin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        '''&lt;Task version=&quot;1.4&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        '''  &lt;RegistrationInfo&gt;
        '''    &lt;Author&gt;WinPaletter&lt;/Author&gt;
        '''    &lt;Description&gt;Play Windows Logoff sound forcibly on Windows 8.1 and higher&lt;/Description&gt;
        '''    &lt;URI&gt;\WinPaletter\Logoff&lt;/URI&gt;
        '''  &lt;/RegistrationInfo&gt;
        '''  &lt;Triggers&gt;
        '''    &lt;EventTrigger&gt;
        '''      &lt;Enabled&gt;true&lt;/Enabled&gt;
        '''      &lt;Subscription&gt;&amp;lt;QueryList&amp;gt;&amp;lt;Query Id=&quot;0&quot; Path=&quot;Security&quot;&amp;gt;&amp;lt;Select Path=&quot;Security&quot;&amp;gt;*[System[Ev [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property XML_Logoff() As String
            Get
                Return ResourceManager.GetString("XML_Logoff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        '''&lt;Task version=&quot;1.4&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        '''  &lt;RegistrationInfo&gt;
        '''    &lt;Author&gt;WinPaletter&lt;/Author&gt;
        '''    &lt;Description&gt;Play Windows Logon sound forcibly on Windows 8.1 and higher&lt;/Description&gt;
        '''    &lt;URI&gt;\WinPaletter\Play logon sound&lt;/URI&gt;
        '''  &lt;/RegistrationInfo&gt;
        '''  &lt;Triggers&gt;
        '''    &lt;LogonTrigger&gt;
        '''      &lt;Enabled&gt;true&lt;/Enabled&gt;
        '''    &lt;/LogonTrigger&gt;
        '''    &lt;SessionStateChangeTrigger&gt;
        '''      &lt;Enabled&gt;true&lt;/Enabled&gt;
        '''      &lt;StateChange&gt;C [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property XML_Logon() As String
            Get
                Return ResourceManager.GetString("XML_Logon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        '''&lt;Task version=&quot;1.4&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        '''  &lt;RegistrationInfo&gt;
        '''    &lt;Author&gt;WinPaletter&lt;/Author&gt;
        '''    &lt;Description&gt;Play Windows Shutdown sound forcibly on Windows 8.1 and higher&lt;/Description&gt;
        '''    &lt;URI&gt;\WinPaletter\Play shutdown sound&lt;/URI&gt;
        '''  &lt;/RegistrationInfo&gt;
        '''  &lt;Triggers&gt;
        '''    &lt;EventTrigger&gt;
        '''      &lt;Enabled&gt;true&lt;/Enabled&gt;
        '''      &lt;Subscription&gt;&amp;lt;QueryList&amp;gt;&amp;lt;Query Id=&quot;0&quot; Path=&quot;System&quot;&amp;gt;&amp;lt;Select Path=&quot;System&quot;&amp;gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property XML_Shutdown() As String
            Get
                Return ResourceManager.GetString("XML_Shutdown", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
