'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WinPaletter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AC_10_Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AC_10_Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AC_10_Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AC_10_Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AC_11_Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AC_11_Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AC_11_Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AC_11_Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ActiveApp_Taskbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActiveApp_Taskbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AeroGlass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AeroGlass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AeroPeek() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AeroPeek", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Animator() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Animator", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property AnimCur() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AnimCur", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AppPreview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppPreview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AppPreviewInActive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppPreviewInActive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BasicTaskbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BasicTaskbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CL_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CL_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CL_Beta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CL_Beta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CL_BugFix() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CL_BugFix", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CL_channel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CL_channel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CL_Date() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CL_Date", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CL_Error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CL_Error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CL_New() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CL_New", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CL_Removed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CL_Removed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CL_Stable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CL_Stable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @RescueBoxAutoClose = Rescue Box - Press any Keyboard Key to disable auto closing
        '''@RescueBox = Rescue Box
        '''@InvalidTheme = Error: Invalid Theme File.
        '''@ThemeNotExist = &quot;Theme File doesn&apos;t exist.&quot;
        '''@OK = OK
        '''@Next_ = Next
        '''@Yes = Yes
        '''@No = No
        '''@NewTag = Create New Theme (Palette) File
        '''@OpenTag = Open a Theme File
        '''@SaveTag = Save Theme File
        '''@SaveAsTag = Save Theme File as ...
        '''@EditInfoTag = Edit Information of current Theme File
        '''@NewUpdate = New Update Avaliable
        '''@OpenForActions = Open Updates form for [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CodeStr() As String
            Get
                Return ResourceManager.GetString("CodeStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ColorThief_Desktop_v46() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ColorThief_Desktop_v46", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Cyotek_Windows_Forms_ColorPicker() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Cyotek_Windows_Forms_ColorPicker", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property darkmode_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("darkmode_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property darkmode_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("darkmode_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property fileextension() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("fileextension", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GaussianBlur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GaussianBlur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GaussianBlurOpaque() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GaussianBlurOpaque", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InactiveApp_Taskbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InactiveApp_Taskbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lightmode_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lightmode_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lightmode_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lightmode_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/blob/master/UpdatesConfig/Changelog?raw=true.
        '''</summary>
        Friend ReadOnly Property Link_Changelog() As String
            Get
                Return ResourceManager.GetString("Link_Changelog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/releases.
        '''</summary>
        Friend ReadOnly Property Link_Releases() As String
            Get
                Return ResourceManager.GetString("Link_Releases", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/.
        '''</summary>
        Friend ReadOnly Property Link_Repository() As String
            Get
                Return ResourceManager.GetString("Link_Repository", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://t.me/WinPaletter.
        '''</summary>
        Friend ReadOnly Property Link_Telegram() As String
            Get
                Return ResourceManager.GetString("Link_Telegram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://github.com/Abdelrhman-AK/WinPaletter/blob/master/UpdatesConfig/Updates?raw=true.
        '''</summary>
        Friend ReadOnly Property Link_Updates() As String
            Get
                Return ResourceManager.GetString("Link_Updates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mini_ACHover_Links() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_ACHover_Links", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mini_Lines_Toggles_Buttons() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_Lines_Toggles_Buttons", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mini_NotUsed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_NotUsed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mini_SettingsIcons() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_SettingsIcons", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mini_Start10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_Start10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mini_Start11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_Start11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mini_StartMenu_Taskbar_AC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_StartMenu_Taskbar_AC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mini_StartMenuAccent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_StartMenuAccent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mini_Taskbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_Taskbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mini_TaskbarActiveIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_TaskbarActiveIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Native10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Native10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Native11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Native11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notify_error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notify_error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notify_info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notify_info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notify_update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notify_update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notify_warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notify_warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows Classic (3.1)|Background=192 192 192|AppWorkspace=255 255 255|Window=255 255 255|WindowText=0 0 0|MenuBar=255 255 255|Menu=255 255 255|MenuText=0 0 0|ActiveTitle=0 0 128|InactiveTitle=255 255 255|TitleText=255 255 255|ActiveBorder=192 192 192|InactiveBorder=192 192 192|WindowFrame=0 0 0|Scrollbar=192 192 192|ButtonFace=192 192 192|ButtonShadow=128 128 128|ButtonText=0 0 0|GrayText=192 192 192|Hilight=0 0 128|HotTrackingColor=0 0 128|MenuHilight=0 0 128|HilightText=255 255 255|InactiveTitleText=0 0 0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RetroThemesDB() As String
            Get
                Return ResourceManager.GetString("RetroThemesDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property settingsfile() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("settingsfile", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Start10_Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start10_Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Start10_Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start10_Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Start11_Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start11_Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Start11_Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start11_Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Start7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Start7Basic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start7Basic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Start7Glass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start7Glass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StartBtn_10Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartBtn_10Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StartBtn_10Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartBtn_10Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StartBtn_11Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartBtn_11Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StartBtn_11Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartBtn_11Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Taskbar_ActiveApp7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Taskbar_ActiveApp7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Taskbar_ActiveApp8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Taskbar_ActiveApp8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Taskbar_InactiveApp7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Taskbar_InactiveApp7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Taskbar_InactiveApp8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Taskbar_InactiveApp8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;WinPaletter - Programmed by Abdelrhman_AK&gt;
        '''*Created from App Version= 1.0.0.0
        '''
        '''&lt;General&gt;
        '''*Palette Name= Windows 10 (Initial)
        '''*Palette Description= (Initial; Like first time after Windows Setup)
        '''*Palette File Version= 1.0
        '''*Author= Microsoft
        '''*AuthorSocialMediaLink= www.microsoft.com
        '''&lt;/General&gt;
        '''
        '''&lt;Toggles&gt;
        '''*WinMode_Light= False
        '''*AppMode_Light= True
        '''*Transparency= True
        '''*Blur= True
        '''*AccentColorOnTitlebarAndBorders= False
        '''*AccentColorOnStartTaskbarAndActionCenter= False
        '''&lt;/Toggles&gt;
        '''
        '''&lt;UWP&gt;
        '''*Tit [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property W10_Init() As String
            Get
                Return ResourceManager.GetString("W10_Init", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;WinPaletter - Programmed by Abdelrhman_AK&gt;
        '''*Created from App Version= 1.0.0.0
        '''
        '''&lt;General&gt;
        '''*Palette Name= Windows 11 (Initial)
        '''*Palette Description= (Initial; Like first time after Windows Setup)
        '''*Palette File Version= 1.0
        '''*Author= Microsoft
        '''*AuthorSocialMediaLink= www.microsoft.com
        '''&lt;/General&gt;
        '''
        '''&lt;Toggles&gt;
        '''*WinMode_Light= True
        '''*AppMode_Light= True
        '''*Transparency= True
        '''*Blur= False
        '''*AccentColorOnTitlebarAndBorders= True
        '''*AccentColorOnStartTaskbarAndActionCenter= False
        '''&lt;/Toggles&gt;
        '''
        '''&lt;UWP&gt;
        '''*Titl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property W11_Init() As String
            Get
                Return ResourceManager.GetString("W11_Init", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Win7_Close_Active() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7_Close_Active", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Win7_Close_inactive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7_Close_inactive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Win7BasicActive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7BasicActive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Win7BasicInactive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7BasicInactive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Win7ORB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7ORB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Win7Sides() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7Sides", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Win7TaskbarSides() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win7TaskbarSides", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Win8ORB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win8ORB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
